# This docker-compose is for local development
version: '3.8'

services:
  # we're not using this yet
  # db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_USER: wallet
  #     POSTGRES_PASSWORD: example
  #     POSTGRES_DB: wallet
  #   ports:
  #     - "127.0.0.1:5432:5432"
  stayup:
    image: ubuntu
    command: tail -f /dev/null

  swagger:
    image: swaggerapi/swagger-ui
    environment:
      SWAGGER_JSON: /app/openapi/fog-wallet.yaml
    ports:
    - "127.0.0.1:8081:8080"
    volumes:
    - ".:/app:ro"

  api:
    build:
      context: .
      dockerfile: ./.dev/Dockerfile
    ports:
    - "127.0.0.1:8080:8080"
    - "127.0.0.1:2345:2345"
    # environment:
      # DB_URL: "postgres://wallet:example@db:5432/wallet?sslmode=disable"
    restart: always
    volumes:
    - ".:/app"
    - "pkg:/go/pkg/"
    # depends_on:
    #   pkg_volume_init:
    #     condition: service_completed_successfully

volumes:
  pkg:
    driver: local
