// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package api

// Account defines model for Account.
type Account struct {
	// Embedded struct due to allOf(#/components/schemas/NewAccount)
	NewAccount `yaml:",inline"`
	// Embedded fields due to inline allOf schema
	// Unique ID of account.
	ID *int64 `gorm:"primarykey" json:"ID,omitempty"`

	// Unique identifier for the account. Constructed from the public key materials of the account key.
	AccountID *string `json:"accountID,omitempty"`

	// I'm testing live updates
	Test *string `json:"test,omitempty"`

	// rad
	Test2 *int64 `json:"test2,omitempty"`
}

// Error defines model for Error.
type Error struct {
	// Error code
	Code int32 `json:"code"`

	// Error message
	Message string `json:"message"`
}

// NewAccount defines model for NewAccount.
type NewAccount struct {
	// Display name for the account.
	Name string `json:"name"`
}

// PostAccountsJSONBody defines parameters for PostAccounts.
type PostAccountsJSONBody NewAccount

// PostAccountsJSONRequestBody defines body for PostAccounts for application/json ContentType.
type PostAccountsJSONRequestBody PostAccountsJSONBody
